import os

CONFIG_PATH = os.path.expanduser("~/.blue_sync_config.json")

PADDING = 10
CORNER_RADIUS = 8
BUTTON_COLOR = "#3a7ebf"
CONNECTED_COLOR = "#4CAF50" 
DISCONNECTED_COLOR = "#607D8B"
SCANNING_COLOR = "#FF9800"
CRITICAL_BATTERY_COLOR = "#FF5252"
NORMAL_BATTERY_COLOR = "#4CAF50"

CRITICAL_BATTERY_THRESHOLD = 20
BATTERY_CHECK_INTERVAL_MS = 60000 